version: '3'
services:
 web:
    image: tds
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net-backend
 db:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=tds
      - POSTGRES_USER=tds_project
      - POSTGRES_PASSWORD=5weber8KLhetruX6
    ports:
    - 5432:5432
    networks:
      - net-backend
    expose:
      - "5432"
    restart: always
    volumes:
        - /tmp/postgres:/var/lib/postgresql/data
networks:
  net-backend: